version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_stream &&
             rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552" # Port for RabbitMQ Streams
    volumes:
      - type: bind
        source: ~/_development/docker-volumes/rabbitmq/data
        target: /var/lib/rabbitmq/mnesia
      - type: bind
        source: ~/_development/docker-volumes/rabbitmq/log
        target: /var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
